#ifndef LRNETJACKSERVERTEST_H
#define LRNETJACKSERVERTEST_H

#include <QtCore/QtGlobal>

#if defined(LRNETJACKSERVERTEST_LIBRARY)
#  define LRNETJACKSERVERTEST_EXPORT Q_DECL_EXPORT
#else
#  define LRNETJACKSERVERTEST_EXPORT Q_DECL_IMPORT
#endif


#endif // LIBJACKSERVERTEST_H
